# Generated by Django 5.1.1 on 2024-09-25 04:20

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_public_id_alter_lesson_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=django_summernote.fields.SummernoteTextField(blank=True, help_text='Content for blog/text lessons', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('BLOG', 'Blog/Text')], default='VIDEO', max_length=10),
        ),
    ]
