# Generated by Django 5.0 on 2024-09-26 15:43

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_public_id_alter_lesson_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=django_summernote.fields.SummernoteTextField(default='', help_text='Content for blog/text lessons'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('BLOG', 'Blog/Text')], default='VIDEO', max_length=10),
        ),
    ]
